[versions]
appcompat = "1.6.1"
gradle-android = "8.0.1"
gradle-dependency-handler-extensions = "1.1.0"

kotlin-core = "1.8.21"
kotlin-detekt = "1.23.0"
kotlin-ktlint-gradle = "11.3.2"
kotlin-ktlint-source = "0.48.2"

[plugins]
gradle-dependency-handler-extensions = { id = "land.sungbin.dependency.handler.extensions", version.ref = "gradle-dependency-handler-extensions" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
kotlin-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "kotlin-detekt" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }

# This isn't strictly used but allows Renovate to see us using the ktlint artifact
kotlin-ktlint = { module = "com.pinterest:ktlint", version.ref = "kotlin-ktlint-source" }

detekt-plugin-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "kotlin-detekt" }
